[package]
name = "image_transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.70"
image = "0.24.6"
ndarray = "0.15.6"
structopt = "0.3.26"
